version: '3.8'

services:
  database:
    container_name: database
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sai 
      - MONGO_INITDB_ROOT_PASSWORD=secret

    # env_file:
    #   - ./env/mongo.env
    

  backend:
    #build: ./backend/Dockerfile
    build: 
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   somearg: 1
    ports:
      - '123:123'
    volumes:
      - logs:/app/logs 
    environment:
      - MONGODB_USERNAME=sai
      - MONGODB_PASSWORD=secret
    # env_file:
    #   - ./env/backend.env
    depends_on:
      - database


    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:1200'
    stdin_open: true
    tty: true
    depends_on:
      - backend





volumes:
  data:
  logs:

